local M = {}

---@type table<string, StillePalette>
M.palettes = {
    dark = {
        bg = "#0f0f0f",
        fg = "#ffffff",

        comment = "#808080",
        keyword = "#ff6347",
        type = "#a3d5f7",
        string = "#7bd88f",
        constant = "#ffffff",
        func = "#ffffff",
        number = "#ffffff",
        operator = "#ffffff",
        cursor = "#ffffff",
        cursorline = "#1a1a1a",

        git_add = "#7bd88f",
        git_add_bg = "#102015",
        git_delete = "#ff8e8e",
        git_delete_bg = "#241217",
        git_change = "#8fbaff",
        git_change_bg = "#12202d",
        git_text_bg = "#1a2c40",

        error = "#ff8e8e",
        warning = "#ffcc66",
        info = "#8fbaff",
        hint = "#7bd88f",
        ok = "#7bd88f",

        black = "#0f0f0f",
        red = "#ff6347",
        green = "#7bd88f",
        yellow = "#ffcc66",
        blue = "#8fbaff",
        magenta = "#d3b1ff",
        cyan = "#a3d5f7",
        white = "#ffffff",
    },
    light = {
        bg = "#faf7f0",
        fg = "#1f2430",

        comment = "#6f7683",
        keyword = "#d89e9e",
        type = "#3f7ea6",
        string = "#4d7f57",
        constant = "#1f2430",
        func = "#1f2430",
        number = "#1f2430",
        operator = "#1f2430",
        cursor = "#9b9b9b",
        cursorline = "#e1dbcd",

        git_add = "#5f8f6b",
        git_add_bg = "#d9eadf",
        git_delete = "#9a4f4f",
        git_delete_bg = "#d89e9e",
        git_change = "#8c7a2b",
        git_change_bg = "#d7d48d",
        git_text_bg = "#e6dfbf",

        error = "#9a4f4f",
        warning = "#8c7a2b",
        info = "#3f7ea6",
        hint = "#5f8f6b",
        ok = "#5f8f6b",

        black = "#faf7f0",
        red = "#d89e9e",
        green = "#4d7f57",
        yellow = "#8c7a2b",
        blue = "#3f7ea6",
        magenta = "#a37acc",
        cyan = "#5c8c8c",
        white = "#1f2430",
    },
    ["no-colors"] = {
        bg = "#000000",
        fg = "#faf7f0",

        comment = "#808080",
        keyword = "#faf7f0",
        type = "#faf7f0",
        string = "#faf7f0",
        constant = "#faf7f0",
        func = "#faf7f0",
        number = "#faf7f0",
        operator = "#faf7f0",
        cursor = "#faf7f0",
        cursorline = "#1a1a1a",

        git_add = "#7bd88f",
        git_add_bg = "#102015",
        git_delete = "#ff8e8e",
        git_delete_bg = "#241217",
        git_change = "#8fbaff",
        git_change_bg = "#12202d",
        git_text_bg = "#1a2c40",

        error = "#faf7f0",
        warning = "#faf7f0",
        info = "#faf7f0",
        hint = "#faf7f0",
        ok = "#faf7f0",

        black = "#000000",
        red = "#faf7f0",
        green = "#faf7f0",
        yellow = "#faf7f0",
        blue = "#faf7f0",
        magenta = "#faf7f0",
        cyan = "#faf7f0",
        white = "#faf7f0",
    },
}

return M
